language: python
python:
  - "3.5"
  - "3.6"

install:
  - python3 setup.py install

# command to run tests
script:
  - cd tests
  - python client_tests.py
  - pip install btfxwss
  - pip install --pre btfxwss


branches:
  only:
  - release-1.1.2